<?xml version="1.0" encoding="UTF-8"?>
<testng-results skipped="0" failed="6" total="14" passed="8">
  <reporter-output>
  </reporter-output>
  <suite name="DealsTest Suite" duration-ms="32252" started-at="2018-04-07T15:06:59Z" finished-at="2018-04-07T15:07:31Z">
    <groups>
    </groups>
    <test name="Deals Test" duration-ms="32252" started-at="2018-04-07T15:06:59Z" finished-at="2018-04-07T15:07:31Z">
      <class name="com.zuora.interview.congjun.testcases.DealsTestCases">
        <test-method status="PASS" signature="beforeSuite()[pri:0, instance:com.zuora.interview.congjun.testcases.DealsTestCases@61a52fbd]" name="beforeSuite" is-config="true" duration-ms="7" started-at="2018-04-07T23:06:59Z" finished-at="2018-04-07T23:06:59Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- beforeSuite -->
        <test-method status="PASS" signature="beforeTest()[pri:0, instance:com.zuora.interview.congjun.testcases.DealsTestCases@61a52fbd]" name="beforeTest" is-config="true" duration-ms="0" started-at="2018-04-07T23:06:59Z" finished-at="2018-04-07T23:06:59Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- beforeTest -->
        <test-method status="PASS" signature="testCreateContacts()[pri:0, instance:com.zuora.interview.congjun.testcases.DealsTestCases@61a52fbd]" name="testCreateContacts" duration-ms="3047" started-at="2018-04-07T23:06:59Z" finished-at="2018-04-07T23:07:02Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- testCreateContacts -->
        <test-method status="PASS" signature="testCreateDeal()[pri:0, instance:com.zuora.interview.congjun.testcases.DealsTestCases@61a52fbd]" name="testCreateDeal" duration-ms="2401" started-at="2018-04-07T23:06:59Z" finished-at="2018-04-07T23:07:01Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- testCreateDeal -->
        <test-method status="PASS" signature="testCreateDealToContactUsingEmailID()[pri:0, instance:com.zuora.interview.congjun.testcases.DealsTestCases@61a52fbd]" name="testCreateDealToContactUsingEmailID" duration-ms="2719" started-at="2018-04-07T23:06:59Z" finished-at="2018-04-07T23:07:02Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- testCreateDealToContactUsingEmailID -->
        <test-method status="FAIL" signature="testGetDealByID()[pri:0, instance:com.zuora.interview.congjun.testcases.DealsTestCases@61a52fbd]" name="testGetDealByID" duration-ms="341" started-at="2018-04-07T23:07:01Z" finished-at="2018-04-07T23:07:01Z">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected:<200> but was:<204>]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected:<200> but was:<204>
	at org.junit.Assert.fail(Assert.java:88)
	at org.junit.Assert.failNotEquals(Assert.java:743)
	at org.junit.Assert.assertEquals(Assert.java:118)
	at org.junit.Assert.assertEquals(Assert.java:555)
	at org.junit.Assert.assertEquals(Assert.java:542)
	at com.zuora.interview.congjun.testcases.DealsTestCases.testGetDealByID(DealsTestCases.java:54)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:84)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:714)
	at org.testng.internal.Invoker.retryFailed(Invoker.java:1049)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1254)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:127)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:111)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- testGetDealByID -->
        <test-method status="FAIL" signature="testBulkDelete()[pri:0, instance:com.zuora.interview.congjun.testcases.DealsTestCases@61a52fbd]" name="testBulkDelete" duration-ms="702" started-at="2018-04-07T23:07:01Z" finished-at="2018-04-07T23:07:02Z">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected:<200> but was:<204>]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected:<200> but was:<204>
	at org.junit.Assert.fail(Assert.java:88)
	at org.junit.Assert.failNotEquals(Assert.java:743)
	at org.junit.Assert.assertEquals(Assert.java:118)
	at org.junit.Assert.assertEquals(Assert.java:555)
	at org.junit.Assert.assertEquals(Assert.java:542)
	at com.zuora.interview.congjun.testcases.DealsTestCases.testBulkDelete(DealsTestCases.java:99)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:84)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:714)
	at org.testng.internal.Invoker.retryFailed(Invoker.java:1049)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1254)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:127)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:111)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- testBulkDelete -->
        <test-method status="PASS" signature="testGetDealsForParticularTrackGroupByMilestone()[pri:0, instance:com.zuora.interview.congjun.testcases.DealsTestCases@61a52fbd]" name="testGetDealsForParticularTrackGroupByMilestone" duration-ms="24975" started-at="2018-04-07T23:07:01Z" finished-at="2018-04-07T23:07:26Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- testGetDealsForParticularTrackGroupByMilestone -->
        <test-method status="PASS" signature="testGetDealsFromDefaultTracGroupByMilestones()[pri:0, instance:com.zuora.interview.congjun.testcases.DealsTestCases@61a52fbd]" name="testGetDealsFromDefaultTracGroupByMilestones" duration-ms="29506" started-at="2018-04-07T23:07:02Z" finished-at="2018-04-07T23:07:31Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- testGetDealsFromDefaultTracGroupByMilestones -->
        <test-method status="FAIL" signature="testGetDealsForParticularTrack()[pri:0, instance:com.zuora.interview.congjun.testcases.DealsTestCases@61a52fbd]" name="testGetDealsForParticularTrack" duration-ms="527" started-at="2018-04-07T23:07:02Z" finished-at="2018-04-07T23:07:02Z">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected:<200> but was:<204>]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected:<200> but was:<204>
	at org.junit.Assert.fail(Assert.java:88)
	at org.junit.Assert.failNotEquals(Assert.java:743)
	at org.junit.Assert.assertEquals(Assert.java:118)
	at org.junit.Assert.assertEquals(Assert.java:555)
	at org.junit.Assert.assertEquals(Assert.java:542)
	at com.zuora.interview.congjun.testcases.DealsTestCases.testGetDealsForParticularTrack(DealsTestCases.java:126)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:84)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:714)
	at org.testng.internal.Invoker.retryFailed(Invoker.java:1049)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1254)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:127)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:111)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- testGetDealsForParticularTrack -->
        <test-method status="PASS" signature="testGetDealsOfCurrentUser()[pri:0, instance:com.zuora.interview.congjun.testcases.DealsTestCases@61a52fbd]" name="testGetDealsOfCurrentUser" duration-ms="1297" started-at="2018-04-07T23:07:02Z" finished-at="2018-04-07T23:07:03Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- testGetDealsOfCurrentUser -->
        <test-method status="PASS" signature="testGetDealsRelateToSpecificContact()[pri:0, instance:com.zuora.interview.congjun.testcases.DealsTestCases@61a52fbd]" name="testGetDealsRelateToSpecificContact" duration-ms="328" started-at="2018-04-07T23:07:02Z" finished-at="2018-04-07T23:07:02Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- testGetDealsRelateToSpecificContact -->
        <test-method status="FAIL" signature="testListDeals()[pri:0, instance:com.zuora.interview.congjun.testcases.DealsTestCases@61a52fbd]" name="testListDeals" duration-ms="600" started-at="2018-04-07T23:07:03Z" finished-at="2018-04-07T23:07:03Z">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected:<200> but was:<500>]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected:<200> but was:<500>
	at org.junit.Assert.fail(Assert.java:88)
	at org.junit.Assert.failNotEquals(Assert.java:743)
	at org.junit.Assert.assertEquals(Assert.java:118)
	at org.junit.Assert.assertEquals(Assert.java:555)
	at org.junit.Assert.assertEquals(Assert.java:542)
	at com.zuora.interview.congjun.testcases.DealsTestCases.testListDeals(DealsTestCases.java:45)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:84)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:714)
	at org.testng.internal.Invoker.retryFailed(Invoker.java:1049)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1254)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:127)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:111)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- testListDeals -->
        <test-method status="FAIL" signature="testRemoveContactsOfDeal()[pri:0, instance:com.zuora.interview.congjun.testcases.DealsTestCases@61a52fbd]" name="testRemoveContactsOfDeal" duration-ms="470" started-at="2018-04-07T23:07:03Z" finished-at="2018-04-07T23:07:03Z">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected:<200> but was:<204>]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected:<200> but was:<204>
	at org.junit.Assert.fail(Assert.java:88)
	at org.junit.Assert.failNotEquals(Assert.java:743)
	at org.junit.Assert.assertEquals(Assert.java:118)
	at org.junit.Assert.assertEquals(Assert.java:555)
	at org.junit.Assert.assertEquals(Assert.java:542)
	at com.zuora.interview.congjun.testcases.DealsTestCases.testRemoveContactsOfDeal(DealsTestCases.java:153)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:84)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:714)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:901)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1231)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:127)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:111)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- testRemoveContactsOfDeal -->
        <test-method status="FAIL" signature="testUpdateDeal()[pri:0, instance:com.zuora.interview.congjun.testcases.DealsTestCases@61a52fbd]" name="testUpdateDeal" duration-ms="273" started-at="2018-04-07T23:07:04Z" finished-at="2018-04-07T23:07:04Z">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected:<200> but was:<204>]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected:<200> but was:<204>
	at org.junit.Assert.fail(Assert.java:88)
	at org.junit.Assert.failNotEquals(Assert.java:743)
	at org.junit.Assert.assertEquals(Assert.java:118)
	at org.junit.Assert.assertEquals(Assert.java:555)
	at org.junit.Assert.assertEquals(Assert.java:542)
	at com.zuora.interview.congjun.testcases.DealsTestCases.testUpdateDeal(DealsTestCases.java:72)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:84)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:714)
	at org.testng.internal.Invoker.retryFailed(Invoker.java:1049)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1254)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:127)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:111)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- testUpdateDeal -->
        <test-method status="PASS" signature="testdeleteDeal()[pri:0, instance:com.zuora.interview.congjun.testcases.DealsTestCases@61a52fbd]" name="testdeleteDeal" duration-ms="591" started-at="2018-04-07T23:07:04Z" finished-at="2018-04-07T23:07:04Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- testdeleteDeal -->
        <test-method status="PASS" signature="afterTest()[pri:0, instance:com.zuora.interview.congjun.testcases.DealsTestCases@61a52fbd]" name="afterTest" is-config="true" duration-ms="1" started-at="2018-04-07T23:07:31Z" finished-at="2018-04-07T23:07:31Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- afterTest -->
        <test-method status="PASS" signature="afterSuite()[pri:0, instance:com.zuora.interview.congjun.testcases.DealsTestCases@61a52fbd]" name="afterSuite" is-config="true" duration-ms="2" started-at="2018-04-07T23:07:31Z" finished-at="2018-04-07T23:07:31Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- afterSuite -->
      </class> <!-- com.zuora.interview.congjun.testcases.DealsTestCases -->
    </test> <!-- Deals Test -->
  </suite> <!-- DealsTest Suite -->
</testng-results>
